CREATE TABLE IF NOT EXISTS public.bulk_open_orders (
    bulk_open_orders_id           integer PRIMARY KEY DEFAULT nextval('bulk_open_orders_bulk_open_orders_id_seq'),
    order_id                      text,
    product_id                    text,
    user_id                       text,
    order_configuration           json,
    side                          text,
    client_order_id               text,
    status                        text,
    time_in_force                 text,
    created_time                  timestamp without time zone,
    completion_percentage         double precision,
    filled_size                   double precision,
    average_filled_price          double precision,
    fee                           text,
    number_of_fills               integer,
    filled_value                  double precision,
    pending_cancel                boolean,
    size_in_quote                 boolean,
    total_fees                    double precision,
    size_inclusive_of_fees        boolean,
    total_value_after_fees        double precision,
    trigger_status                text,
    order_type                    text,
    reject_reason                 text,
    settled                       boolean,
    product_type                  text,
    reject_message                text,
    cancel_message                text,
    order_placement_source        text,
    outstanding_hold_amount       double precision,
    is_liquidation                boolean,
    last_fill_time                timestamp without time zone,
    edit_history                  json,
    leverage                      text,
    margin_type                   text,
    retail_portfolio_id           text,
    originating_order_id          text,
    attached_order_id             text,
    attached_order_configuration  json,
    current_pending_replace       json,
    commission_detail_total       json,
    workable_size                 text,
    workable_size_completion_pct  text,
    product_details               json,
    cost_basis_method             text,
    displayed_order_config        text,
    equity_trading_session        text,
    prediction_side               text,
    last_update_time              timestamp without time zone
);
