CREATE TABLE IF NOT EXISTS public.position (
    stock_id               integer,
    name                   text,
    shares                 double precision,
    date_created           timestamp without time zone,
    error_message          text,
    period_type            text,
    buy_filled_price       double precision,
    buy_price              double precision,
    sell_price             double precision,
    buy_order_id           text,
    sell_order_id          text,
    buy_coinbase_order_id  text,
    sell_coinbase_order_id text,
    buy_stop_price         double precision,
    sell_stop_price        double precision,
    sell_filled_price      double precision,
    buy_fee                double precision,
    sell_fee               double precision,
    profit                 double precision,
    daily_sell             boolean NOT NULL DEFAULT false,
    sell_counter           integer NOT NULL DEFAULT 0,
    buy_counter            integer NOT NULL DEFAULT 0
);
